"""Agentic morning briefing for power & gas trading.

Implements a multi-step agentic workflow that orchestrates:
  1. **Data Collection** — Weather, electricity demand, NG storage,
     commodity prices from multiple APIs.
  2. **Demand Forecasting** — Runs the trained load forecast model
     to predict next-day/week electricity demand.
  3. **RAG Context Retrieval** — Queries the energy trading knowledge
     base for relevant fundamental and seasonal context.
  4. **News Sentiment** — Pulls latest energy news sentiment.
  5. **LLM Synthesis** — Combines all gathered intelligence into a
     structured, professional morning trading briefing.

This architecture demonstrates agentic AI: the system autonomously
decides which data to gather, which questions to ask the knowledge base,
and how to synthesise findings — rather than following a rigid template.

Target audience: Power & gas trading desk, Eastern/Central US markets.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ====================================================================== #
#  Prompts
# ====================================================================== #

BRIEFING_SYSTEM_PROMPT = """\
You are a senior power and natural gas market analyst preparing the daily
morning briefing for the trading desk.  Your audience trades physical and
financial power and gas across US markets (PJM, MISO, NYIS, ISNE, CISO,
ERCO, SWPP).

Write with authority.  Be specific with numbers.  Flag actionable items.
"""

BRIEFING_SYNTHESIS_PROMPT = """\
Generate a structured morning trading briefing for {date}.

═══════════════════════════════════════════════════════════
SECTION 1 — MARKET DATA (latest prices & changes)
═══════════════════════════════════════════════════════════
{market_data}

═══════════════════════════════════════════════════════════
SECTION 2 — WEATHER & DEMAND OUTLOOK
═══════════════════════════════════════════════════════════
{weather_demand_outlook}

═══════════════════════════════════════════════════════════
SECTION 3 — DEMAND FORECAST (ML model output)
═══════════════════════════════════════════════════════════
{demand_forecast}

═══════════════════════════════════════════════════════════
SECTION 4 — KNOWLEDGE BASE CONTEXT (RAG retrieval)
═══════════════════════════════════════════════════════════
{rag_context}

═══════════════════════════════════════════════════════════
SECTION 5 — NEWS SENTIMENT
═══════════════════════════════════════════════════════════
{sentiment_summary}

═══════════════════════════════════════════════════════════

Write the briefing in the following format (500-700 words):

## Power & Gas Morning Briefing — {date}

### Executive Summary
[3-4 sentences: overnight moves, key driver, desk action items]

### Weather & Load Outlook
[Temperature forecast for the Eastern Interconnection, HDD/CDD impact
on demand, model-predicted load vs recent actuals, any unusual patterns]

### Natural Gas Fundamentals
[Storage vs 5-year average, production, LNG exports, demand drivers,
gas-for-power demand implications from the load forecast]

### Power Market Dynamics
[Regional observations for PJM/MISO/NYIS/ISNE/CISO/ERCO/SWPP, congestion,
outages, renewable generation outlook if relevant]

### Key Risks & Catalysts
[Top 3 upside risks, top 3 downside risks for the session]

### Trade Ideas
[1-2 specific actionable trade ideas with rationale tied to the
demand forecast and fundamental context.  Include direction, instrument,
and time horizon.]

---
*Generated by Energy Trading AI — agentic briefing with RAG-augmented*
*context from {n_rag_sources} knowledge base sources.*"""


# RAG queries that the agent autonomously selects based on market conditions
RAG_QUERY_TEMPLATES = {
    "seasonal_patterns": (
        "What seasonal patterns affect {market} demand and pricing "
        "during {month}?  How do weather patterns impact load?"
    ),
    "gas_storage": (
        "How do natural gas storage levels and injection/withdrawal patterns "
        "affect gas and power pricing?  What is the historical relationship?"
    ),
    "gas_power_nexus": (
        "How does natural gas demand for power generation affect gas prices?  "
        "What drives gas-for-power demand in {region}?"
    ),
    "extreme_weather": (
        "How do extreme weather events (heat waves, polar vortex, cold snaps) "
        "affect electricity demand and power prices across US ISOs?"
    ),
    "market_fundamentals": (
        "What are the key fundamental drivers of electricity prices in "
        "PJM, MISO, NYISO, CAISO, ERCOT, and SPP?  How do fuel costs, demand, and supply interact?"
    ),
    "risk_factors": (
        "What are the biggest risk factors for power and gas markets?  "
        "What geopolitical, regulatory, or infrastructure risks should traders watch?"
    ),
}


@dataclass
class BriefingState:
    """Tracks the state of the agentic briefing generation pipeline.

    Each attribute represents the output of one agent step.
    """

    date: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    market_data: dict[str, Any] = field(default_factory=dict)
    weather_outlook: dict[str, Any] = field(default_factory=dict)
    demand_forecast: dict[str, Any] = field(default_factory=dict)
    rag_contexts: list[dict[str, str]] = field(default_factory=list)
    sentiment: dict[str, Any] = field(default_factory=dict)
    briefing_text: str = ""
    steps_completed: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


class MorningBriefingAgent:
    """Agentic morning briefing generator for power & gas trading.

    Orchestrates a multi-step pipeline where each step autonomously
    gathers and analyses data from different sources, then synthesises
    everything into a professional trading briefing using an LLM with
    RAG-augmented context from the energy trading knowledge base.

    Architecture:
        Step 1: collect_market_data()   → prices, storage, fundamentals
        Step 2: collect_weather()       → weather + HDD/CDD outlook
        Step 3: run_demand_forecast()   → ML model load prediction
        Step 4: query_knowledge_base()  → RAG retrieval (autonomous queries)
        Step 5: collect_sentiment()     → news sentiment analysis
        Step 6: synthesise_briefing()   → LLM generation

    Attributes:
        llm_client: LLM interface for generation.
        qa_chain: RAG QA chain for knowledge base access.
        retriever: Document retriever for direct RAG queries.
        load_model_path: Path to trained load forecast model.
    """

    def __init__(
        self,
        llm_client,
        qa_chain=None,
        retriever=None,
        load_model_path: str | Path | None = None,
        prices_fetcher=None,
    ) -> None:
        """Initialise the morning briefing agent.

        Args:
            llm_client: ``LLMClient`` instance for text generation.
            qa_chain: Optional ``QAChain`` for RAG Q&A.
            retriever: Optional ``Retriever`` for direct context retrieval.
            load_model_path: Path to a saved ``XGBLoadForecaster`` model.
            prices_fetcher: Optional ``PriceFetcher`` for live price data.
        """
        self.llm_client = llm_client
        self.qa_chain = qa_chain
        self.retriever = retriever
        self.load_model_path = Path(load_model_path) if load_model_path else None
        self.prices_fetcher = prices_fetcher
        self._load_model = None
        logger.info("MorningBriefingAgent initialised")

    # ------------------------------------------------------------------ #
    #  Main entry point
    # ------------------------------------------------------------------ #
    def run(self, date: datetime | None = None) -> str:
        """Execute the full agentic briefing pipeline.

        Each step is independent and fault-tolerant — if one step fails,
        the briefing is still generated with available data.

        Args:
            date: Briefing date.  Defaults to today (UTC).

        Returns:
            Formatted morning briefing as markdown string.
        """
        state = BriefingState(date=date or datetime.now(timezone.utc))
        date_str = state.date.strftime("%A, %d %B %Y")

        logger.info("═" * 60)
        logger.info("Morning Briefing Agent — %s", date_str)
        logger.info("═" * 60)

        # Step 1: Market data
        logger.info("Step 1/6: Collecting market data...")
        self._step_collect_market_data(state)

        # Step 2: Weather outlook
        logger.info("Step 2/6: Collecting weather data...")
        self._step_collect_weather(state)

        # Step 3: Demand forecast
        logger.info("Step 3/6: Running demand forecast model...")
        self._step_demand_forecast(state)

        # Step 4: RAG knowledge base queries
        logger.info("Step 4/6: Querying knowledge base (RAG)...")
        self._step_query_knowledge_base(state)

        # Step 5: News sentiment
        logger.info("Step 5/6: Collecting news sentiment...")
        self._step_collect_sentiment(state)

        # Step 6: Synthesise
        logger.info("Step 6/6: Synthesising briefing with LLM...")
        self._step_synthesise(state)

        logger.info("Briefing complete — %d steps, %d errors",
                     len(state.steps_completed), len(state.errors))
        return state.briefing_text

    # ------------------------------------------------------------------ #
    #  Step 1 — Market Data
    # ------------------------------------------------------------------ #
    def _step_collect_market_data(self, state: BriefingState) -> None:
        """Collect latest commodity prices and NG storage."""
        try:
            data: dict[str, Any] = {}

            # Try to fetch live prices
            if self.prices_fetcher is not None:
                try:
                    tickers = {
                        "Natural Gas (NG)": "natural_gas",
                        "WTI Crude": "wti",
                        "Brent Crude": "brent",
                        "Heating Oil": "heating_oil",
                        "RBOB Gasoline": "rbob_gasoline",
                    }
                    prices = {}
                    changes = {}
                    fetched = self.prices_fetcher.fetch(
                        symbols=list(tickers.values()),
                    )
                    for display_name, key in tickers.items():
                        df = fetched.get(key)
                        if df is not None and len(df) >= 2:
                            prices[display_name] = float(df["Close"].iloc[-1])
                            prev = float(df["Close"].iloc[-2])
                            changes[display_name] = (
                                (prices[display_name] - prev) / prev
                            ) * 100
                    data["prices"] = prices
                    data["changes"] = changes
                except Exception as exc:
                    logger.warning("Price fetch failed: %s", exc)

            # Try to fetch NG storage from EIA
            try:
                from src.data.eia_client import EIAClient

                eia = EIAClient()
                storage = eia.fetch_nat_gas_storage()
                if not storage.empty:
                    data["ng_storage_bcf"] = float(storage.iloc[-1].values[0])
                    data["ng_storage_date"] = str(storage.index[-1].date())
                    surprise = eia.compute_storage_surprise(storage)
                    if "surprise" in surprise.columns:
                        data["ng_storage_surprise"] = float(
                            surprise["surprise"].dropna().iloc[-1]
                        )
            except Exception as exc:
                logger.warning("EIA storage fetch failed: %s", exc)

            state.market_data = data
            state.steps_completed.append("market_data")
        except Exception as exc:
            state.errors.append(f"market_data: {exc}")
            logger.error("Step 1 failed: %s", exc)

    # ------------------------------------------------------------------ #
    #  Step 2 — Weather
    # ------------------------------------------------------------------ #
    def _step_collect_weather(self, state: BriefingState) -> None:
        """Collect recent weather data and compute outlook."""
        try:
            from src.data.openmeteo_client import OpenMeteoClient

            client = OpenMeteoClient()
            end_date = (state.date - timedelta(days=2)).strftime("%Y-%m-%d")
            start_date = (state.date - timedelta(days=14)).strftime("%Y-%m-%d")
            weather = client.fetch_weather(start=start_date, end=end_date)

            if weather.empty:
                state.errors.append("weather: no data returned")
                return

            recent = weather.tail(7)
            outlook = {
                "latest_date": str(weather.index[-1].date()),
                "tavg_latest": round(float(weather["tavg"].iloc[-1]), 1),
                "tavg_7d_avg": round(float(recent["tavg"].mean()), 1),
                "hdd_7d_total": round(float(recent["hdd"].sum()), 1),
                "cdd_7d_total": round(float(recent["cdd"].sum()), 1),
                "temp_trend": "warming" if float(weather["tavg"].diff().tail(3).mean()) > 0 else "cooling",
                "hdd_latest": round(float(weather["hdd"].iloc[-1]), 1),
                "cdd_latest": round(float(weather["cdd"].iloc[-1]), 1),
            }

            state.weather_outlook = outlook
            state.steps_completed.append("weather")
        except Exception as exc:
            state.errors.append(f"weather: {exc}")
            logger.error("Step 2 failed: %s", exc)

    # ------------------------------------------------------------------ #
    #  Step 3 — Demand Forecast
    # ------------------------------------------------------------------ #
    def _step_demand_forecast(self, state: BriefingState) -> None:
        """Run the trained demand model for next-day load prediction."""
        try:
            if self.load_model_path is None or not self.load_model_path.exists():
                state.demand_forecast = {"status": "no model available"}
                state.steps_completed.append("demand_forecast_skipped")
                return

            # Load model
            if self._load_model is None:
                from src.models.load_forecaster import XGBLoadForecaster
                self._load_model = XGBLoadForecaster.load(self.load_model_path)

            # Load recent features for prediction
            features_path = Path("data/processed/load_features.csv")
            if not features_path.exists():
                state.demand_forecast = {"status": "no feature data"}
                return

            df = pd.read_csv(features_path, index_col=0, parse_dates=True)
            feature_cols = [c for c in df.columns if c != "target"]
            recent = df.tail(7)

            X_latest = recent[feature_cols].fillna(0).values
            preds = self._load_model.predict(X_latest)

            actual_recent = recent["target"].dropna().values
            predicted_latest = float(preds[-1]) if len(preds) > 0 else None
            actual_latest = float(actual_recent[-1]) if len(actual_recent) > 0 else None

            # Compute recent model accuracy
            if len(preds) > 1 and len(actual_recent) > 1:
                min_len = min(len(preds), len(actual_recent))
                recent_mape = float(
                    np.mean(np.abs(
                        (actual_recent[:min_len] - preds[:min_len]) / actual_recent[:min_len]
                    )) * 100
                )
            else:
                recent_mape = None

            forecast = {
                "status": "ok",
                "predicted_total_mwh": predicted_latest,
                "recent_actual_mwh": actual_latest,
                "recent_7d_mape": recent_mape,
                "model": self._load_model.name,
                "forecast_date": str(recent.index[-1].date()),
            }

            # Add directional context
            if predicted_latest and actual_latest:
                pct_change = ((predicted_latest - actual_latest) / actual_latest) * 100
                forecast["change_vs_yesterday_pct"] = round(pct_change, 2)
                if pct_change > 2:
                    forecast["direction"] = "demand increasing"
                elif pct_change < -2:
                    forecast["direction"] = "demand decreasing"
                else:
                    forecast["direction"] = "demand stable"

            state.demand_forecast = forecast
            state.steps_completed.append("demand_forecast")
        except Exception as exc:
            state.errors.append(f"demand_forecast: {exc}")
            logger.error("Step 3 failed: %s", exc)

    # ------------------------------------------------------------------ #
    #  Step 4 — RAG Knowledge Base (Autonomous Query Selection)
    # ------------------------------------------------------------------ #
    def _step_query_knowledge_base(self, state: BriefingState) -> None:
        """Query the RAG knowledge base with context-appropriate questions.

        The agent autonomously selects which queries to run based on
        current market conditions (e.g.  if temperatures are extreme,
        it queries for extreme weather impacts).
        """
        if self.qa_chain is None and self.retriever is None:
            state.errors.append("rag: no QA chain or retriever available")
            return

        try:
            month_name = state.date.strftime("%B")
            queries_to_run = self._select_rag_queries(state, month_name)

            for query_name, query_text in queries_to_run.items():
                try:
                    if self.qa_chain is not None:
                        result = self.qa_chain.ask(query_text, top_k=3, return_sources=True)
                        state.rag_contexts.append({
                            "query": query_name,
                            "answer": result.get("answer", ""),
                            "n_sources": len(result.get("sources", [])),
                        })
                    elif self.retriever is not None:
                        chunks = self.retriever.retrieve(query_text, top_k=3)
                        context = "\n".join(
                            c.get("text", "")[:300] for c in chunks[:2]
                        )
                        state.rag_contexts.append({
                            "query": query_name,
                            "answer": context,
                            "n_sources": len(chunks),
                        })
                except Exception as exc:
                    logger.warning("RAG query '%s' failed: %s", query_name, exc)

            state.steps_completed.append("rag_queries")
            logger.info("RAG: completed %d knowledge base queries", len(state.rag_contexts))
        except Exception as exc:
            state.errors.append(f"rag: {exc}")
            logger.error("Step 4 failed: %s", exc)

    def _select_rag_queries(
        self, state: BriefingState, month: str
    ) -> dict[str, str]:
        """Autonomously select which RAG queries to run based on context.

        This is the "agentic" part — the system decides what information
        it needs from the knowledge base based on current market state.
        """
        queries = {}

        # Always query seasonal patterns and fundamentals
        queries["seasonal_patterns"] = RAG_QUERY_TEMPLATES["seasonal_patterns"].format(
            market="power and gas", month=month,
        )
        queries["market_fundamentals"] = RAG_QUERY_TEMPLATES["market_fundamentals"]

        # Query gas storage if we have storage data
        if state.market_data.get("ng_storage_bcf"):
            queries["gas_storage"] = RAG_QUERY_TEMPLATES["gas_storage"]

        # Query extreme weather if conditions are extreme
        weather = state.weather_outlook
        if weather:
            tavg = weather.get("tavg_latest", 65)
            if tavg < 25 or tavg > 90:
                queries["extreme_weather"] = RAG_QUERY_TEMPLATES["extreme_weather"]

        # Query gas-power nexus (always relevant for power/gas desk)
        queries["gas_power_nexus"] = RAG_QUERY_TEMPLATES["gas_power_nexus"].format(
            region="PJM, MISO, ERCOT, and CAISO",
        )

        # Query risk factors
        queries["risk_factors"] = RAG_QUERY_TEMPLATES["risk_factors"]

        logger.info("Agent selected %d RAG queries: %s",
                     len(queries), list(queries.keys()))
        return queries

    # ------------------------------------------------------------------ #
    #  Step 5 — Sentiment
    # ------------------------------------------------------------------ #
    def _step_collect_sentiment(self, state: BriefingState) -> None:
        """Collect recent energy news sentiment."""
        try:
            try:
                from src.nlp.sentiment import SentimentAnalyzer
                from src.data.news_fetcher import NewsFetcher

                fetcher = NewsFetcher()
                articles = fetcher.fetch_energy_news(days_back=2)
                if articles:
                    analyzer = SentimentAnalyzer()
                    scores = []
                    headlines = []
                    for art in articles[:20]:
                        title = art.get("title", "")
                        score = analyzer.analyze(title)
                        scores.append(score.get("compound", 0))
                        headlines.append(title)

                    avg_sentiment = float(np.mean(scores)) if scores else 0.0
                    state.sentiment = {
                        "score": round(avg_sentiment, 3),
                        "regime": "bullish" if avg_sentiment > 0.1 else (
                            "bearish" if avg_sentiment < -0.1 else "neutral"
                        ),
                        "n_articles": len(articles),
                        "top_headlines": headlines[:5],
                    }
                else:
                    state.sentiment = {"score": 0.0, "regime": "neutral", "n_articles": 0}
            except Exception:
                state.sentiment = {"score": 0.0, "regime": "neutral", "n_articles": 0}

            state.steps_completed.append("sentiment")
        except Exception as exc:
            state.errors.append(f"sentiment: {exc}")
            logger.error("Step 5 failed: %s", exc)

    # ------------------------------------------------------------------ #
    #  Step 6 — LLM Synthesis
    # ------------------------------------------------------------------ #
    def _step_synthesise(self, state: BriefingState) -> None:
        """Synthesise all gathered data into a structured briefing."""
        try:
            date_str = state.date.strftime("%A, %d %B %Y")

            # Format market data section
            market_text = self._format_market_data(state.market_data)

            # Format weather/demand outlook
            weather_text = self._format_weather_outlook(state.weather_outlook)

            # Format demand forecast
            forecast_text = self._format_demand_forecast(state.demand_forecast)

            # Format RAG context
            rag_text, n_sources = self._format_rag_context(state.rag_contexts)

            # Format sentiment
            sentiment_text = self._format_sentiment(state.sentiment)

            prompt = BRIEFING_SYNTHESIS_PROMPT.format(
                date=date_str,
                market_data=market_text,
                weather_demand_outlook=weather_text,
                demand_forecast=forecast_text,
                rag_context=rag_text,
                sentiment_summary=sentiment_text,
                n_rag_sources=n_sources,
            )

            state.briefing_text = self.llm_client.complete(
                user_message=prompt,
                system_prompt=BRIEFING_SYSTEM_PROMPT,
            )
            state.steps_completed.append("synthesis")
        except Exception as exc:
            state.errors.append(f"synthesis: {exc}")
            logger.error("Step 6 failed: %s", exc)
            # Fallback: structured text without LLM
            state.briefing_text = self._fallback_briefing(state)

    # ------------------------------------------------------------------ #
    #  Formatting helpers
    # ------------------------------------------------------------------ #
    @staticmethod
    def _format_market_data(data: dict) -> str:
        if not data:
            return "Market data not available."
        lines = []
        prices = data.get("prices", {})
        changes = data.get("changes", {})
        for name, price in prices.items():
            chg = changes.get(name, 0)
            sign = "+" if chg >= 0 else ""
            lines.append(f"  {name}: ${price:.2f} ({sign}{chg:.2f}%)")
        if data.get("ng_storage_bcf"):
            lines.append(f"\n  NG Storage: {data['ng_storage_bcf']:.0f} Bcf "
                          f"(as of {data.get('ng_storage_date', 'N/A')})")
            if data.get("ng_storage_surprise"):
                lines.append(f"  Storage Surprise: {data['ng_storage_surprise']:+.1f} Bcf")
        return "\n".join(lines) if lines else "No market data collected."

    @staticmethod
    def _format_weather_outlook(data: dict) -> str:
        if not data:
            return "Weather data not available."
        lines = [
            f"  Population-Weighted Avg Temp (Eastern US): {data.get('tavg_latest', 'N/A')}°F",
            f"  7-Day Average Temp: {data.get('tavg_7d_avg', 'N/A')}°F",
            f"  Temperature Trend: {data.get('temp_trend', 'N/A')}",
            f"  7-Day HDD Total: {data.get('hdd_7d_total', 'N/A')}",
            f"  7-Day CDD Total: {data.get('cdd_7d_total', 'N/A')}",
            f"  Today HDD: {data.get('hdd_latest', 'N/A')} | CDD: {data.get('cdd_latest', 'N/A')}",
        ]
        return "\n".join(lines)

    @staticmethod
    def _format_demand_forecast(data: dict) -> str:
        if not data or data.get("status") != "ok":
            return f"Demand forecast: {data.get('status', 'unavailable')}"
        lines = [
            f"  Model: {data.get('model', 'N/A')}",
            f"  Forecast Date: {data.get('forecast_date', 'N/A')}",
            f"  Predicted Total Demand: {data.get('predicted_total_mwh', 0):,.0f} MWh",
            f"  Recent Actual Demand: {data.get('recent_actual_mwh', 0):,.0f} MWh",
        ]
        if data.get("change_vs_yesterday_pct") is not None:
            lines.append(
                f"  Change vs Yesterday: {data['change_vs_yesterday_pct']:+.1f}% "
                f"({data.get('direction', 'N/A')})"
            )
        if data.get("recent_7d_mape") is not None:
            lines.append(f"  Recent 7-Day MAPE: {data['recent_7d_mape']:.2f}%")
        return "\n".join(lines)

    @staticmethod
    def _format_rag_context(contexts: list[dict]) -> tuple[str, int]:
        if not contexts:
            return "Knowledge base not queried.", 0
        lines = []
        total_sources = 0
        for ctx in contexts:
            query = ctx.get("query", "unknown")
            answer = ctx.get("answer", "")[:500]
            n = ctx.get("n_sources", 0)
            total_sources += n
            lines.append(f"  [{query}] ({n} sources):\n    {answer}\n")
        return "\n".join(lines), total_sources

    @staticmethod
    def _format_sentiment(data: dict) -> str:
        if not data:
            return "Sentiment data not available."
        lines = [
            f"  Overall Sentiment: {data.get('score', 0):.3f} "
            f"({data.get('regime', 'neutral').upper()})",
            f"  Articles Analysed: {data.get('n_articles', 0)}",
        ]
        headlines = data.get("top_headlines", [])
        if headlines:
            lines.append("  Top Headlines:")
            for h in headlines[:3]:
                lines.append(f"    • {h}")
        return "\n".join(lines)

    @staticmethod
    def _fallback_briefing(state: BriefingState) -> str:
        """Generate a simple text briefing without LLM (fallback)."""
        date_str = state.date.strftime("%A, %d %B %Y")
        sections = [
            f"## Power & Gas Morning Briefing — {date_str}",
            "",
            "### Status",
            f"Steps completed: {', '.join(state.steps_completed)}",
            f"Errors: {len(state.errors)}",
        ]
        if state.weather_outlook:
            sections.extend([
                "",
                "### Weather",
                f"Avg temp: {state.weather_outlook.get('tavg_latest')}°F, "
                f"Trend: {state.weather_outlook.get('temp_trend')}",
            ])
        if state.demand_forecast.get("status") == "ok":
            sections.extend([
                "",
                "### Demand Forecast",
                f"Predicted: {state.demand_forecast.get('predicted_total_mwh', 0):,.0f} MWh",
            ])
        sections.append("\n---\n*Fallback briefing (LLM synthesis failed)*")
        return "\n".join(sections)
